# Stage 1: Build React app
FROM node:18-alpine AS builder
WORKDIR /app

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

COPY package.json ./
RUN npm install
COPY . .

RUN npm run build

# Stage 2: Serve static files
FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/build ./build
EXPOSE 80 3000
CMD ["serve", "-s", "build", "-l", "3000"]