version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "25565:25565"
      - "3002:3002"
    volumes:
      - ./server:/app/server
      - ./data:/app/data
      #- .:/app # Монтирование кода для разработки
    env_file:
      - .env
    restart: always
    command: >
      sh -c "if [ ! -d node_modules ]; then npm install; fi && node index.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://api:3001
    depends_on:
      - api
    restart: always
    profiles:
      - "frontend"