version: "3"
name: mcstack
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - minecraft-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "25565:25565"
      - "3002:3002"
    volumes:
      - ./server:/app/server
      - ./data:/app/data
      - ./config:/app/config
      # - .:/app # Монтирование кода (для разработки)
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    restart: always
    command: >
      sh -c "if [ ! -d node_modules ]; then npm install; fi && node index.js"
    networks:
      - minecraft-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://api:3001
    depends_on:
      - api
    restart: always
    profiles:
      - "frontend"
    networks:
      - minecraft-network

networks:
  minecraft-network: