version: "3"
name: mcstack

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - minecraft-network
    profiles:
      - "local-redis"
      - "all"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "25565:25565"
      - "3002:3002"
    volumes:
      - ./server:/app/server
      - ./data:/app/data
      - ./config:/app/config
      # - .:/app # Монтирование кода (для разработки)
    env_file:
      - .env
    environment:
      DISABLE_REDIS: ${DISABLE_REDIS:-0}
      REDIS_HOST: ${REDIS_HOST:-redis}
    restart: always
    command: >
      sh -c "if [ ! -d node_modules ]; then npm install; fi && node index.js"
    networks:
      - minecraft-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:3001}
        # Тут передаётся адрес во фронтенд
        # Если вы хотите использовать DNS имя, то введите: - REACT_APP_API_URL: https://my-dns-name.ru/
        # Порт на фронтенде по дефолтку используется 3001, его также нужно указывать
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - api
    restart: always
    profiles:
      - "frontend"
      - "all"
    networks:
      - minecraft-network

networks:
  minecraft-network:
